baseURL = "https://www.qcooperative.net"
languageCode = "en-us"
title = "QCooperative"
theme = "meghna-hugo"
summaryLength = 10

[taxonomies]
  author = "author"
  category = "categories"
  tag = "tags"

# Menu
[menu]
    [[menu.nav]]
    name = "About Us"
    URL = "about"
    weight = 2

    [[menu.nav]]
    name = "Services"
    URL = "services"
    weight = 3

    [[menu.nav]]
    name = "Team"
    URL = "our-team"
    weight = 5

    [[menu.nav]]
    name = "Blog"
    URL = "blog"
    weight = 7

    [[menu.nav]]
    name = "Contact"
    URL = "contact-us"
    weight = 8

# Site params
[params]
home= "Home"
logo = "images/logo.png"
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
# Meta data
description = "Responsive Multipurpose Parallax HTML5 Template"
author = "Themefisher"
# Google Analitycs
googleAnalitycsID = "Your ID"
custom_css = ["css/custom.css"]

    # Banner Section
    [params.banner]
    enable = true
    bgImage = "images/slider/hero-area.jpg"
    icon = "tf-ion-play"
    heading = "Supported Open Source GIS?"
    content= "Do want to use Open Source for GIS, but you are afraid to do it on your own?"
    btn = true
    btnText="We can help"
    btnURL="#about"

    # call to action
    [params.cta]
    enable = true
    title = "The right team"
    content = "We are an international team of professional QGIS developers, trainers, testers and documenters working together to provide each client the spatial services he needs"
    btnURL = "#contact-us"
    btnText = "Start a project with us"

    # counter
    [params.counter]
    enable = true
    bgImage = "images/backgrounds/bg-1.jpg"
        [[params.counter.counterItem]]
        title = "QGIS Commits"
        icon = "tf-ion-archive"
        count = "320"

        [[params.counter.counterItem]]
        title = "Trainings"
        icon = "tf-ion-android-happy"
        count = "565"

        [[params.counter.counterItem]]
        title = "Positive feedback"
        icon = "tf-ion-thumbsup"
        count = "95"

        [[params.counter.counterItem]]
        title = "Slices of Pizza"
        icon = "tf-ion-coffee"
        count = "2500"

    # footer
    [params.footer]
        copyright = "Themefisher Team"
        copyrightURL = "http://www.themefisher.com"

        # social Icons
        [[params.footer.socialIcon]]
        icon = "tf-ion-social-facebook"
        url = "#"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-twitter"
        url = "#"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-google-outline"
        url = "#"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-youtube"
        url = "#"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-linkedin"
        url = "#"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-dribbble-outline"
        url = "#"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-pinterest-outline"
        url = "#"
